module.exports=`abhivādana-paccuṭṭhāna-añjali-kamma-sāmīci-kamma-cīvara-piṇḍapāta-senāsana-gilāna-ppaccaya-bhesajja-parikkhārān-uppadānena
abhivādana-paccuṭṭhāna-añjali-kamma-sāmīci-kamma-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārān-uppadānenā
tulākūṭa-kaṃsakūṭa-mānakūṭa-ukkoṭana-vañcana-nikati-sāci-yoga-chedana-vadhabandhana-viparāmosa-ālopa-sahasākārā
kusal-ākusala-sāvajjā-navajja-sevitabb-āsevitabba-hīna-paṇīta-kaṇha-sukka-sappaṭibhāgānaṃ
nacca-gīta-vādita-visūka-dassana-mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānaṃ
nacca-gīta-vādita-visūka-dassana-mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānā
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārān-uppadānatthaṃ
itarītara-cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārena
daṇḍādāna-satthādāna-kalaha-viggaha-vivāda-tuvaṃtuvaṃ-pesuñña-musāvādānaṃ
itarītara-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārena
itarītara-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārenā
daṇḍādāna-satthādāna-kalaha-viggaha-vivāda-tuvaṃtuvaṃ-pesuñña-musāvādā
Diṭṭhi-rāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosāna-hetu
Kāmarāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosāna-hetu
cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhāra-hetu
diṭṭhi-rāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosānaṃ
cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārenāti
catubbidha-vacīkammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
cīvarapiṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārānan
cīvarapiṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārānaṃ
cīvarapiṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārena
cīvarapiṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārehi
kāmarāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosānaṃ
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārānaṃ
cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārenā
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārānan
cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhāran
cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhāraṃ
Tividha-kāyakammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
tividha-kāyakammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
tividha-manokammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārehi
cīvara-piṇḍapāta-senāsana-gilānap-paccaya-bhesajja-parikkhārā
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārā
anicc-ucchādana-parimaddana-bhedana-viddhaṃsana-dhammassa
itarītara-gilānap-paccaya-bhesajja-parikkhāra-santuṭṭhiyā
diṭṭhiṭṭh-ānādhiṭṭhāna-pariyuṭṭhānā-bhinives-ānusayānaṃ
catubbidha-vacīkammanta-sampatti-kusala-sañcetanikā-hetu
Appaṭinissagge-ukkhepanīya-kamma-paṭippassaddhi-kathā
anicc-ucchādana-parimaddana-bhedana-viddhaṃsana-dhammo
vaccamagga-passāvamagga-methunadhammap-paṭisaṃyuttā
asandiṭṭhi-parāmāsi-anādhānaggāhi-suppaṭi-nissaggitā
Tividha-kāyakammanta-sampatti-kusala-sañcetanikā-hetu
tividha-manokammanta-sampatti-kusala-sañcetanikā-hetu
tividha-kāyakammanta-sampatti-kusala-sañcetanikā-hetu
mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānā
Mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānā
dakkha-kammāra-putta-ukkāmukha-sukusala-sampahaṭṭhaṃ
soka-parideva-dukkha-domanass-upāyāsa-saṃvattanikesu
soka-parideva-dukkha-domanass-upāyāsa-saṃvattanikepi
Appaṭikamme-ukkhepanīya-kamma-paṭippassaddhi-kathā
sandiṭṭhi-parāmāsi-ādhānaggāhi-dup-paṭinissaggissa
Sandiṭṭhi-parāmāsi-ādhānaggāhi-dup-paṭinissaggissa
Chedana-vadhabandhana-viparāmosa-ālopa-sahasākārā
chedana-vadhabandhana-viparāmosa-ālopa-sahasākārā
abhivādana-paccuṭṭhāna-añjalikamma-sāmīcikammānī
paralābha-sakkāragarukā-ramāna-navandana-pūjanāsu
soka-parideva-dukkha-domanass-upāyāsa-pariḷāhenapi
abhivādana-paccuṭṭhāna-añjalikamma-sāmīcikammaṃ
samaṇa-brāhmaṇa-kapaṇaddhika-vaṇibbaka-yācakānaṃ
byāpannacitta-paduṭṭhamana-saṅkappa-sandosa-hetu
bheri-paṇavavaṃsa-saṅkhaḍiṇ-ḍima-ninnāda-saddānaṃ
samaṇa-brāhmaṇa-kapaṇaddhika-vanibbaka-yācakānaṃ
samaṇa-brāhmaṇa-kapaṇaddhika-vanibbaka-yācakānan
soka-parideva-dukkha-domanass-upāyāsan-dhakārampi
kalaha-viggaha-vivāda-tuvaṃtuvaṃ-pesuñña-musāvādā
Adassane-ukkhepanīya-kamma-paṭippassaddhi-kathā
Parimaṇḍala-anonama-jaṇṇu-pari-masana-lakkhaṇāni
attahita-parahita-ubhayahita-sabba-lokahitameva
Sāvajja-kāyakammanta-vacīkammanta-manokammanto
Vīmaṃsā-samādhip-padhāna-saṅkhāra-samannāgataṃ
Soka-parideva-dukkha-domanass-upāyāsa-dhammānaṃ
soka-parideva-dukkha-domanass-upāyāsa-dhammānaṃ
vīmaṃsā-samādhip-padhāna-saṅkhāra-samannāgataṃ
soka-parideva-dukkha-domanass-upāyāsa-papātampi
Khetta-kammanta-sāmanta-sabyohārānukam-pitassa
Appaṭi-nissagge-ukkhepanīya-kamma-vivāda-kathā
anupubbābhi-saññā-nirodha-sampajāna-samāpatti
chanda-samādhip-padhāna-saṅkhāra-samannāgataṃ
Vīriyasamādhippadhānasaṅkhārasamannāgataṃ
vīmaṃsā-samādhi-padhāna-saṅkhāra-samannāgataṃ
Vīmaṃsā-samādhi-padhāna-saṅkhāra-samannāgataṃ
samādhija-pīti-sukhas-sāda-saṃyojana-saṃyuttaṃ
vīmaṃsa-samādhi-padhāna-saṅkhāra-samannāgataṃ
vīriya-samādhip-padhāna-saṅkhāra-samannāgataṃ
vīmaṃsā-samādhip-padhāna-saṅkhāra-samannāgato
appa-ḍaṃsa-makasa-vātātapa-sarīsapa-samphassaṃ
Cittas-amādhi-ppadhāna-saṅkhāra-samannāgataṃ
chanda-samādhi-padhāna-saṅkhāra-samannāgataṃ
vīriya-samādhi-padhāna-saṅkhāra-samannāgataṃ
utuparissaya-vinodana-paṭisallān-ārām-atthaṃ
Vīriya-samādhi-padhāna-saṅkhāra-samannāgataṃ
vivekaja-pīti-sukh-assāda-saṃyojana-saṃyuttaṃ
aññatitthiya-samaṇa-brāhmaṇa-paribbājakānaṃ
ḍaṃsa-makasa-vātātapa-sarīsapa-samphassenapi
citta-samādhip-padhāna-saṅkhāra-samannāgataṃ
chanda-samādhip-padhāna-saṅkhāra-samannāgato
vīriya-samādhip-padhāna-saṅkhāra-samannāgato
Chanda-samādhi-padhāna-saṅkhāra-samannāgataṃ
Puttadāra-dāsakamma-karaporis-ānukampitassa
Pathavikathā-pasuta-pañcasata-bhikkhuvatthu
ḍaṃsa-makasa-vātātapa-sarīsapa-samphassānaṃ
samādhija-pīti-sukha-sukhuma-sacca-saññīyeva
papañca-saññ-āsaṅkhā-nirodha-sārupp-agāminiṃ
soka-parideva-dukkha-domanass-upāyāsa-dhammā
citta-samādhi-padhāna-saṅkhāra-samannāgataṃ
Citta-samādhi-padhāna-saṅkhāra-samannāgataṃ
Ḍaṃsa-makasa-vātātapa-sarīsapa-samphassānaṃ
papañca-saññ-āsaṅkhā-samudā-caraṇa-paññattiṃ
Diṭṭha-dhamm-ābhiññāvosāna-pāramip-pattānaṃ
diṭṭha-suta-muta-viññātabba-saṅkhāra-mattena
citta-samādhip-padhāna-saṅkhāra-samannāgato
Appaṭikamme-ukkhepanīya-kamma-vivāda-kathā
vivekaja-pīti-sukha-sukhuma-sacca-saññīyeva
hijjhālu-kāmesu-tibbasā-rāga-sandosa-hetu
ḍaṃsa-makasa-vātāta-pasarīsapa-samphassehi
ucchādana-parimaddana-nhāpana-sambāhanena
bheri-paṇava-saṅkhati-ṇava-ninnāda-saddānaṃ
Pamattā-pamatta-dve-sahāyaka-bhikkhu-vatthu
ākāsānañcāyatana-sukhuma-sacca-saññīyeva
viññāṇañcāyatana-sukhuma-sacca-saññīyeva
lābhasakkāra-siloka-nikāmana-sandosa-hetu
Mahācūḷa-dukkhakkhandha-anumānika-suttaṃ
mahā-taṇhā-jāla-taṇhā-saṅghāṭap-paṭimukkan
adukkham-asukhas-sāda-saṃyojana-saṃyuttaṃ
bheri-paṇava-saṅkhati-ṇava-ninnādasaddena
ucchādana-parimaddana-nhāpana-sambāhanaṃ
Mahākassapat-thera-piṇḍapāta-dinna-vatthu
Kassapa-dasabalas-sasu-vaṇṇa-cetiya-vatthu
gilānap-paccaya-bhesajja-parikkhāra-hetu
ḍaṃsa-makasa-vātātapa-sarīsapa-samphasso
Paṭisāraṇīya-kamma-paṭippassaddhi-kathā
nappaṭip-passambhetabba-tecattālīsakaṃ
Sappitela-navanīta-dadhi-madhu-phāṇitena
pariyāya-bhatta-bhojan-ānuyogam-anuyutto
ākiñcaññ-āyatana-sukhuma-sacca-saññīyeva
Citta-hatthi-sāriputta-poṭṭhapāda-vatthu
Kāyānupassanā-paṭikūla-manasikāra-pabba
Asammā-sambuddh-appa-vedita-dhamma-vinaya
Khila-pattha-madhu-piṇḍika-dvidhā-vitakka
pariyāya-bhatta-bhojan-ānuyogam-anuyuttā
diṭṭha-dhamm-ābhiññā-vosāna-pāramip-pattā
saṅkhārā-vasesa-samāpatti-pattabbametaṃ
nevasaññā-n-āsaññāyatana-paṭisaṃyuttāya
sabba-rāga-dosa-moha-nihita-ninnīta-kasāvo
jāti-jarā-maraṇa-dukkha-samudaya-sambhavo
dhamma-nimitt-assāda-saṃyojana-saṃyuttaṃ
saṃyojan-ābhinivesa-vinibandh-ājjhosānā
Gocara-mūlaka-abhinīhāra-suttā-dicatukka
Sakkacca-mūlaka-sātaccakārī-sutta-dukādi
surā-meraya-majjap-pamādaṭṭhānap-paccayā
bheri-paṇava-saṅkhati-ṇava-ninnādasaddaṃ
caṇḍālaku-māraka-caṇḍālaku-mārikā-samena
Saṅgharakkhita-bhāgineyyat-thera-vatthu
Kosambi-vāsi-tissat-thera-sāmaṇera-vatthu
Sambahula-sīlādisampanna-bhikkhu-vatthu`+

//shorter than 36but with frequency >10
`gilānap-paccaya-bhesajja-parikkhāra-hetu
pariyāya-bhatta-bhojan-ānuyogam-anuyutto
soka-parideva-dukkha-domanass-upāyāsehi
gilānap-paccaya-bhesajja-parikkhāraṃ
soka-parideva-dukkha-domanass-upāyāsā
jhāna-vimokkha-samādhi-samāpattīnaṃ
yathā-bhūta-ñāṇa-dassana-sampannassa
saññā-vedayita-nirodha-samāpattiyā
Saññā-vedayita-nirodha-samāpattiyā
vijjā-vimutti-phala-sacchikiriyāya
yathābhūta-ñāṇa-dassana-vipannassa
nātta-paritāpan-ānuyogam-anuyutto
uddhacca-kukkucca-pariyuṭṭhitena
Paṭhama-āmaka-dhañña-peyyāla-vagga
sakadāgāmi-phala-sacchikiriyāya
dvattiṃsa-mahāpurisa-lakkhaṇāni
dvattiṃsa-mahāpurisa-lakkhaṇehi
atta-paritāpan-ānuyogam-anuyutto
para-paritāpan-ānuyogam-anuyutto
adhammacariyā-visamacariyā-hetu
Dutiya-āmakadhañña-peyyāla-vagga
Tatiya-āmakadhañña-peyyāla-vagga
vimutti-ñāṇa-dassanak-khandhena
sotāpatti-phala-sacchikiriyāya
surā-meraya-majjap-pamādaṭṭhānā
lokāyata-mahāpurisa-lakkhaṇesu
ahaṅkāra-mamaṅkāra-mānāpagataṃ
surā-meraya-majja-pamādaṭṭhānaṃ
evaṃ-sukha-dukkhap-paṭisaṃvedī
paraloka-vajja-bhayadassāvine
alamariya-ñāṇadassana-visesaṃ
surā-meraya-majja-pamādaṭṭhānā
tassa-pāpiya-sikā-kammārahassa
saṃghādises-āpattik-khandhena
bījagāma-bhūtagāma-samārambhā
dhamma-vicaya-sambojjhaṅgassa
Adhammacariyā-visamacariyāhi
ahaṅkāra-mamaṅkāram-ānānusayā
surā-meraya-majja-pamādaṭṭhāyī
ayoniso-manasikāra-bahulīkāro
Sagāthaka-puññābhisanda-vagga
saṅghāṭi-patta-cīvara-dhāraṇaṃ
nevasaññā-n-āsaññāyatana-saññī
anāgāmi-phala-sacchikiriyāya
thullaccay-āpattik-khandhena
diṭṭhadhamma-sukha-vihārānaṃ
parama-diṭṭha-dhamma-nibbānaṃ
paritassita-vipphanditameva
saṅghāṭi-patta-cīvara-dhāraṇe
udakorohan-ānuyogam-anuyutto
itarītara-cīvara-santuṭṭhiyā
alam-ariya-ñāṇa-dassana-viseso
vimutti-ñāṇa-dassana-sampanno
macchera-mala-pariyuṭṭhitena
yoniso-manasikāra-bahulīkāro
Dhamma-cakkap-pavattana-vagga
adhipaññā-dhamma-vipassanāya
micchā-diṭṭhi-kamma-samādānā
sabba-pāṇa-bhūta-hit-ānukampī
uddhacca-kukkucca-nīvaraṇaṃ
dhamma-vicaya-sambojjhaṅgaṃ
samudaya-vaya-dhamm-ānupassī
diṭṭha-dhamma-sukha-vihārāya
atītānāgata-paccuppannānaṃ
adhammacariyā-visamacariyā
abhiññāvosāna-pāramip-pattā
adhiṭṭhān-ābhinives-ānusayā
Dutiya-samaṇa-brāhmaṇa-sutta
diṭṭha-dhamma-nibbānap-patto
pabbata-kandara-padara-sākhā
thina-middha-pariyuṭṭhitena
pubbenivās-ānussati-ñāṇāya
sammādiṭṭhi-kamma-samādānā
pātimokkha-saṃvara-saṃvuto
parikkhīṇa-bhava-saṃyojano
paṭisāraṇīya-kammārahassa
patta-cīvarap-paṭiggahaṇaṃ
Yathā-paṭicchann-ānañcassa
diṭṭha-dhamma-sukha-vihāraṃ
pācittiy-āpattikkhandhena
janapad-atthā-variyap-patto
khīṇāpāya-duggativinipāto
dhammānudhammap-paṭipannā
dhammānudhammap-paṭipanno
dhamma-vicaya-sambojjhaṅgo
passaddhi-sambojjhaṅgassa
dhammānudhammap-paṭipatti
jarā-maraṇa-nirodh-agāminiṃ
parikkhīṇa-bhava-saṃyojanā
vicikicchā-pariyuṭṭhitena
caturāsīti-vassa-sahassāni
abhiññā-sacchikaraṇīyassa
seyyāva-satha-padīpeyyassa
yoniso-manasikāra-sampanno
kabaḷīkār-āhāra-bhakkhānaṃ
brahmacariya-pariyosānaṃ
atītānāgata-paccuppannaṃ
aparisuddha-kāya-samācāro
aparisuddha-vacī-samācāro
pabbājanīya-kammārahassa
ukkhepanīya-kammārahassa
nappaṭip-passambhetabbaṃ
bhikkhun-ovādaka-sammutiṃ
mūlāya-paṭikassan-ārahena
pārājik-āpattik-khandhena
nevasaññā-n-āsaññāyatanaṃ
paranimmita-vasavattīnaṃ
sammā-sambuddhap-pavedito
diṭṭhi-nijjhānak-khantiyā
vimutti-ñāṇa-dassana-kathā
Dutiya-gaṅgāpeyyāla-vagga
nibbidā-virāga-vipannassa
sammā-samādhi-sampannassa
avippaṭisāra-sampannassa
paracitta-pariyāya-kusalo
upekkhā-sati-pārisuddhiṃ
addhāna-maggap-paṭipanno
uttari-manussa-dhammassa
dāsakamma-kara-porisassa
Nisīdana-paccattharaṇaṃ
addhāna-maggap-paṭipannā
ceto-parivitakka-maññāya
sabb-ūpadhi-paṭinissaggo
atīt-ānāgata-paccup-pannā
cakkhu-samphassa-paccayā
parisuddha-kāya-samācāro
parisuddha-vacī-samācāro
bhikkhun-ovādaka-sammuti
dvemāsap-paṭicchannānaṃ
dukkaṭ-āpatti-kkhandhena
yathābhūta-ñāṇa-dassanaṃ
sammā-manasikāra-manvāya
cātuyāma-saṃvara-saṃvuto
sattaratana-samannāgato
piṇḍapāta-paṭikkantānaṃ
passaddhi-sambojjhaṅgaṃ
samādhi-sambojjhaṅgassa
upekkhā-sambojjhaṅgassa
saṅkhār-upādānakkhandho
paccuppanna-dukkhañceva
seyyā-vasatha-padīpeyyaṃ
saṅkhāra-nirodh-agāminiṃ
tiṇa-kaṭṭha-sākhāpalāsaṃ
dhammacariyā-samacariyā
kāmarāga-pariyuṭṭhitena
ākāsānañcāyatana-saññaṃ
viññāṇañcāyatana-saññaṃ
chandarāga-vinay-akkhāyī
Aṭṭhasata-pariyāya-vagga
nevasaññā-āsaññāyatane
iddhipāda-bhāvan-āgāminī
mahāpuññak-khandhotveva
uṭṭhāna-vīriy-ādhigatehi
sammā-samādhi-vipannassa
avippaṭisāra-vipannassa
sikkhā-sājīva-samāpanno
uttari-chappañca-vācāhi
punabbhav-ābhinibbatti
somanassa-domanassānaṃ
gāmanigama-rājadhānīsu
anullapan-ādhippāyassā
mālāguḷa-parikkhittāpi
jivhā-samphassa-paccayā
brāhmaṇa-gaha-patikānaṃ
mūlāya-paṭikassan-āraho
gilān-upaṭṭhāka-bhattaṃ
dukkha-nirodh-agāminiyā
tassa-pāpiyasikā-kammaṃ
tajjanīya-kamm-ārahassa
paṭisāraṇīya-kammakato
pañcāhap-paṭicchannāya
dvemāsap-paṭicchannāyo
dvemāsap-paṭicchannāya
citta-vipariyāsa-katena
diṭṭha-suta-parisaṅkito
paṭinissajjana-paccayā
samādhi-saṃvattanikāni
anusandhi-vacana-pathaṃ
uccāsayana-mahāsayanaṃ
vipariṇām-aññathābhāvā
icchānaṅgala-vanasaṇḍe
saññā-vedayita-nirodhaṃ
samādhi-saṃvattanikehi
rattandhakā-ratimisāya
hemajāla-paṭicchannāni
brahma-loka-sahabyatāya
Samudaya-dhammānupassī
vīriya-sambojjhaṅgassa
passaddhi-sambojjhaṅgo
viññāṇ-upādānakkhandho
manussa-rāhasseyyakāni
brahmacariy-ānuggahāya
tatth-ev-antara-dhāyiṃsu
paccuppanna-sukhañceva
sasaṅkhāra-parinibbāyī
ākāsānañcāyatana-saññā
viññāṇañcāyatana-saññā
passaddhakāya-saṅkhāro
viññāṇa-nirodh-agāminiṃ
samudaya-dhammānupassī
paligha-parivatti-kampi
byāpāda-pariyuṭṭhitena
diṭṭha-dhamma-vedanīyaṃ
abhiññā-sacchikiriyāya
ākiñcaññāyatana-saññaṃ
mālāgandha-vilepanassa
sāriputta-moggallānesu
dhamma-cakkhu-paṭilābho
rāga-vinaya-pariyosānaṃ
dosa-vinaya-pariyosānaṃ
moha-vinaya-pariyosānaṃ
aṭṭhika-saññā-sahagataṃ
Pañcagati-peyyāla-vagga
āroha-pariṇāha-sampanno
upapatti-paṭilābhiyāni
yathābhūta-ñāṇa-dassane
ākāsānañcāyatana-saññī
viññāṇañcāyatana-saññī
sacitta-pariyāya-kusalo`+
`āpatti-samuṭṭhānānaṃ
piṇḍapāta-paṭikkanto
atikkanta-mānusakena
dukkha-nirodh-agāminī
uttari-manussa-dhammaṃ
saññā-vedayita-nirodhaṃ
samādhi-saṃvattanikehi
brahmacariya-pariyosānaṃ
dhammānudhammap-paṭipannā
dhammānudhammap-paṭipanno
dhammavicaya-sambojjhaṅgo
diṭṭhadhamma-sukha-vihārānaṃ`;