module.exports=`abhivādana-paccuṭṭhāna-añjali-kamma-sāmīci-kamma-cīvara-piṇḍapāta-senāsana-gilāna-ppaccaya-bhesajja-parikkhārān-uppadānena
abhivādana-paccuṭṭhāna-añjali-kamma-sāmīci-kamma-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārān-uppadānenā
tulākūṭa-kaṃsakūṭa-mānakūṭa-ukkoṭana-vañcana-nikati-sāci-yoga-chedana-vadhabandhana-viparāmosa-ālopa-sahasākārā
kusal-ākusala-sāvajjā-navajja-sevitabb-āsevitabba-hīna-paṇīta-kaṇha-sukka-sappaṭibhāgānaṃ
nacca-gīta-vādita-visūka-dassana-mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānaṃ
nacca-gīta-vādita-visūka-dassana-mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānā
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārān-uppadānatthaṃ
itarītara-cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārena
daṇḍādāna-satthādāna-kalaha-viggaha-vivāda-tuvaṃtuvaṃ-pesuñña-musāvādānaṃ
itarītara-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārena
itarītara-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārenā
daṇḍādāna-satthādāna-kalaha-viggaha-vivāda-tuvaṃtuvaṃ-pesuñña-musāvādā
Diṭṭhi-rāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosāna-hetu
Kāmarāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosāna-hetu
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhāra-hetu
diṭṭhi-rāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosānaṃ
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārenāti
catubbidha-vacīkammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
cīvarapiṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārānan
cīvarapiṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārānaṃ
cīvarapiṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārena
cīvarapiṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārehi
kāmarāgā-bhinivesa-vinibandha-paligedha-pariyuṭṭhān-ajjhosānaṃ
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārānaṃ
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārenā
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārānan
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhāran
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhāraṃ
Tividha-kāyakammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
tividha-kāyakammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
tividha-manokammanta-sandosa-byāpatti-akusala-sañcetanikā-hetu
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārehi
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārā
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārā
anicc-ucchādana-parimaddana-bhedana-viddhaṃsana-dhammassa
itarītara-gilāna-p-paccaya-bhesajja-parikkhāra-santuṭṭhiyā
diṭṭhiṭṭh-ānādhiṭṭhāna-pariyuṭṭhānā-bhinives-ānusayānaṃ
catubbidha-vacīkammanta-sampatti-kusala-sañcetanikā-hetu
Appaṭinissagge-ukkhepanīya-kamma-paṭippassaddhi-kathā
anicc-ucchādana-parimaddana-bhedana-viddhaṃsana-dhammo
vaccamagga-passāvamagga-methunadhammap-paṭisaṃyuttā
asandiṭṭhi-parāmāsi-anādhānaggāhi-suppaṭi-nissaggitā
Tividha-kāyakammanta-sampatti-kusala-sañcetanikā-hetu
tividha-manokammanta-sampatti-kusala-sañcetanikā-hetu
tividha-kāyakammanta-sampatti-kusala-sañcetanikā-hetu
mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānā
Mālā-gandha-vilepana-dhāraṇa-maṇḍana-vibhūsanaṭṭhānā
dakkha-kammāra-putta-ukkāmukha-sukusala-sampahaṭṭhaṃ
soka-parideva-dukkha-domanass-upāyāsa-saṃvattanikesu
soka-parideva-dukkha-domanass-upāyāsa-saṃvattanikepi
Appaṭikamme-ukkhepanīya-kamma-paṭippassaddhi-kathā
sandiṭṭhi-parāmāsi-ādhānaggāhi-du-p-paṭinissaggissa
Sandiṭṭhi-parāmāsi-ādhānaggāhi-du-p-paṭinissaggissa
Chedana-vadhabandhana-viparāmosa-ālopa-sahasākārā
chedana-vadhabandhana-viparāmosa-ālopa-sahasākārā
abhivādana-paccuṭṭhāna-añjalikamma-sāmīcikammānī
paralābha-sakkāragarukā-ramāna-navandana-pūjanāsu
soka-parideva-dukkha-domanass-upāyāsa-pariḷāhenapi
abhivādana-paccuṭṭhāna-añjalikamma-sāmīcikammaṃ
samaṇa-brāhmaṇa-kapaṇaddhika-vaṇibbaka-yācakānaṃ
byāpannacitta-paduṭṭhamana-saṅkappa-sandosa-hetu
bheri-paṇavavaṃsa-saṅkhaḍiṇ-ḍima-ninnāda-saddānaṃ
samaṇa-brāhmaṇa-kapaṇaddhika-vanibbaka-yācakānaṃ
samaṇa-brāhmaṇa-kapaṇaddhika-vanibbaka-yācakānan
soka-parideva-dukkha-domanass-upāyāsan-dhakārampi
kalaha-viggaha-vivāda-tuvaṃtuvaṃ-pesuñña-musāvādā
Adassane-ukkhepanīya-kamma-paṭippassaddhi-kathā
Parimaṇḍala-anonama-jaṇṇu-pari-masana-lakkhaṇāni
attahita-parahita-ubhayahita-sabba-lokahitameva
Sāvajja-kāyakammanta-vacīkammanta-manokammanto
Vīmaṃsā-samādhi-p-padhāna-saṅkhāra-samannāgataṃ
Soka-parideva-dukkha-domanass-upāyāsa-dhammānaṃ
soka-parideva-dukkha-domanass-upāyāsa-dhammānaṃ
vīmaṃsā-samādhi-p-padhāna-saṅkhāra-samannāgataṃ
soka-parideva-dukkha-domanass-upāyāsa-papātampi
Khetta-kammanta-sāmanta-sabyohārānukam-pitassa
Appaṭi-nissagge-ukkhepanīya-kamma-vivāda-kathā
anupubbābhi-saññā-nirodha-sampajāna-samāpatti
chanda-samādhi-p-padhāna-saṅkhāra-samannāgataṃ
Vīriyasamādhippadhānasaṅkhārasamannāgataṃ
vīmaṃsā-samādhi-padhāna-saṅkhāra-samannāgataṃ
Vīmaṃsā-samādhi-padhāna-saṅkhāra-samannāgataṃ
samādhija-pīti-sukha-s-sāda-saṃyojana-saṃyuttaṃ
vīmaṃsa-samādhi-padhāna-saṅkhāra-samannāgataṃ
vīriya-samādhi-p-padhāna-saṅkhāra-samannāgataṃ
vīmaṃsā-samādhi-p-padhāna-saṅkhāra-samannāgato
appa-ḍaṃsa-makasa-vātātapa-sarīsapa-samphassaṃ
Cittas-amādhi-ppadhāna-saṅkhāra-samannāgataṃ
chanda-samādhi-padhāna-saṅkhāra-samannāgataṃ
vīriya-samādhi-padhāna-saṅkhāra-samannāgataṃ
utuparissaya-vinodana-paṭisallān-ārām-atthaṃ
Vīriya-samādhi-padhāna-saṅkhāra-samannāgataṃ
vivekaja-pīti-sukh-assāda-saṃyojana-saṃyuttaṃ
aññatitthiya-samaṇa-brāhmaṇa-paribbājakānaṃ
ḍaṃsa-makasa-vātātapa-sarīsapa-samphassenapi
citta-samādhi-p-padhāna-saṅkhāra-samannāgataṃ
chanda-samādhi-p-padhāna-saṅkhāra-samannāgato
vīriya-samādhi-p-padhāna-saṅkhāra-samannāgato
Chanda-samādhi-padhāna-saṅkhāra-samannāgataṃ
Puttadāra-dāsakamma-karaporis-ānukampitassa
Pathavikathā-pasuta-pañcasata-bhikkhuvatthu
ḍaṃsa-makasa-vātātapa-sarīsapa-samphassānaṃ
samādhija-pīti-sukha-sukhuma-sacca-saññīyeva
papañca-saññ-āsaṅkhā-nirodha-sārupp-agāminiṃ
soka-parideva-dukkha-domanass-upāyāsa-dhammā
citta-samādhi-padhāna-saṅkhāra-samannāgataṃ
Citta-samādhi-padhāna-saṅkhāra-samannāgataṃ
Ḍaṃsa-makasa-vātātapa-sarīsapa-samphassānaṃ
papañca-saññ-āsaṅkhā-samudā-caraṇa-paññattiṃ
Diṭṭha-dhamm-ābhiññāvosāna-pārami-p-pattānaṃ
diṭṭha-suta-muta-viññātabba-saṅkhāra-mattena
citta-samādhi-p-padhāna-saṅkhāra-samannāgato
Appaṭikamme-ukkhepanīya-kamma-vivāda-kathā
vivekaja-pīti-sukha-sukhuma-sacca-saññīyeva
hijjhālu-kāmesu-tibbasā-rāga-sandosa-hetu
ḍaṃsa-makasa-vātāta-pasarīsapa-samphassehi
ucchādana-parimaddana-nhāpana-sambāhanena
bheri-paṇava-saṅkhati-ṇava-ninnāda-saddānaṃ
Pamattā-pamatta-dve-sahāyaka-bhikkhu-vatthu
ākāsānañcāyatana-sukhuma-sacca-saññīyeva
viññāṇañcāyatana-sukhuma-sacca-saññīyeva
lābhasakkāra-siloka-nikāmana-sandosa-hetu
Mahācūḷa-dukkhakkhandha-anumānika-suttaṃ
mahā-taṇhā-jāla-taṇhā-saṅghāṭa-p-paṭimukkan
adukkham-asukha-s-sāda-saṃyojana-saṃyuttaṃ
bheri-paṇava-saṅkhati-ṇava-ninnādasaddena
ucchādana-parimaddana-nhāpana-sambāhanaṃ
Mahākassapa-t-thera-piṇḍapāta-dinna-vatthu
Kassapa-dasabala-s-sasu-vaṇṇa-cetiya-vatthu
gilāna-p-paccaya-bhesajja-parikkhāra-hetu
ḍaṃsa-makasa-vātātapa-sarīsapa-samphasso
Paṭisāraṇīya-kamma-paṭippassaddhi-kathā
nappaṭi-p-passambhetabba-tecattālīsakaṃ
Sappitela-navanīta-dadhi-madhu-phāṇitena
pariyāya-bhatta-bhojan-ānuyogam-anuyutto
ākiñcaññ-āyatana-sukhuma-sacca-saññīyeva
Citta-hatthi-sāriputta-poṭṭhapāda-vatthu
Kāyānupassanā-paṭikūla-manasikāra-pabba
Asammā-sambuddh-appa-vedita-dhamma-vinaya
Khila-pattha-madhu-piṇḍika-dvidhā-vitakka
pariyāya-bhatta-bhojan-ānuyogam-anuyuttā
diṭṭha-dhamm-ābhiññā-vosāna-pārami-p-pattā
saṅkhārā-vasesa-samāpatti-pattabbametaṃ
nevasaññā-n-āsaññāyatana-paṭisaṃyuttāya
sabba-rāga-dosa-moha-nihita-ninnīta-kasāvo
jāti-jarā-maraṇa-dukkha-samudaya-sambhavo
dhamma-nimitt-assāda-saṃyojana-saṃyuttaṃ
saṃyojan-ābhinivesa-vinibandh-ājjhosānā
Gocara-mūlaka-abhinīhāra-suttā-dicatukka
Sakkacca-mūlaka-sātaccakārī-sutta-dukādi
surā-meraya-majja-p-pamādaṭṭhāna-p-paccayā
bheri-paṇava-saṅkhati-ṇava-ninnādasaddaṃ
caṇḍālaku-māraka-caṇḍālaku-mārikā-samena
Saṅgharakkhita-bhāgineyya-t-thera-vatthu
Kosambi-vāsi-tissa-t-thera-sāmaṇera-vatthu
Sambahula-sīlādisampanna-bhikkhu-vatthu`+

//shorter than 36but with frequency >10
`gilāna-p-paccaya-bhesajja-parikkhāra-hetu
pariyāya-bhatta-bhojan-ānuyogam-anuyutto
soka-parideva-dukkha-domanass-upāyāsehi
gilāna-p-paccaya-bhesajja-parikkhāraṃ
soka-parideva-dukkha-domanass-upāyāsā
jhāna-vimokkha-samādhi-samāpattīnaṃ
yathā-bhūta-ñāṇa-dassana-sampannassa
saññā-vedayita-nirodha-samāpattiyā
Saññā-vedayita-nirodha-samāpattiyā
vijjā-vimutti-phala-sacchikiriyāya
yathābhūta-ñāṇa-dassana-vipannassa
nātta-paritāpan-ānuyogam-anuyutto
uddhacca-kukkucca-pariyuṭṭhitena
Paṭhama-āmaka-dhañña-peyyāla-vagga
sakadāgāmi-phala-sacchikiriyāya
dvattiṃsa-mahāpurisa-lakkhaṇāni
dvattiṃsa-mahāpurisa-lakkhaṇehi
atta-paritāpan-ānuyogam-anuyutto
para-paritāpan-ānuyogam-anuyutto
adhammacariyā-visamacariyā-hetu
Dutiya-āmakadhañña-peyyāla-vagga
Tatiya-āmakadhañña-peyyāla-vagga
vimutti-ñāṇa-dassana-k-khandhena
sotāpatti-phala-sacchikiriyāya
surā-meraya-majja-p-pamādaṭṭhānā
lokāyata-mahāpurisa-lakkhaṇesu
ahaṅkāra-mamaṅkāra-mānāpagataṃ
surā-meraya-majja-pamādaṭṭhānaṃ
evaṃ-sukha-dukkha-p-paṭisaṃvedī
paraloka-vajja-bhayadassāvine
alamariya-ñāṇadassana-visesaṃ
surā-meraya-majja-pamādaṭṭhānā
tassa-pāpiya-sikā-kammārahassa
saṃghādises-āpatti-k-khandhena
bījagāma-bhūtagāma-samārambhā
dhamma-vicaya-sambojjhaṅgassa
Adhammacariyā-visamacariyāhi
ahaṅkāra-mamaṅkāram-ānānusayā
surā-meraya-majja-pamādaṭṭhāyī
ayoniso-manasikāra-bahulīkāro
Sagāthaka-puññābhisanda-vagga
saṅghāṭi-patta-cīvara-dhāraṇaṃ
nevasaññā-n-āsaññāyatana-saññī
anāgāmi-phala-sacchikiriyāya
thullaccay-āpatti-k-khandhena
diṭṭhadhamma-sukha-vihārānaṃ
parama-diṭṭha-dhamma-nibbānaṃ
paritassita-vipphanditameva
saṅghāṭi-patta-cīvara-dhāraṇe
udakorohan-ānuyogam-anuyutto
itarītara-cīvara-santuṭṭhiyā
alam-ariya-ñāṇa-dassana-viseso
vimutti-ñāṇa-dassana-sampanno
macchera-mala-pariyuṭṭhitena
yoniso-manasikāra-bahulīkāro
Dhamma-cakka-p-pavattana-vagga
adhipaññā-dhamma-vipassanāya
micchā-diṭṭhi-kamma-samādānā
sabba-pāṇa-bhūta-hit-ānukampī
uddhacca-kukkucca-nīvaraṇaṃ
dhamma-vicaya-sambojjhaṅgaṃ
samudaya-vaya-dhamm-ānupassī
diṭṭha-dhamma-sukha-vihārāya
atītānāgata-paccuppannānaṃ
adhammacariyā-visamacariyā
abhiññāvosāna-pārami-p-pattā
adhiṭṭhān-ābhinives-ānusayā
Dutiya-samaṇa-brāhmaṇa-sutta
diṭṭha-dhamma-nibbāna-p-patto
pabbata-kandara-padara-sākhā
thina-middha-pariyuṭṭhitena
pubbenivās-ānussati-ñāṇāya
sammādiṭṭhi-kamma-samādānā
pātimokkha-saṃvara-saṃvuto
parikkhīṇa-bhava-saṃyojano
paṭisāraṇīya-kammārahassa
patta-cīvara-p-paṭiggahaṇaṃ
Yathā-paṭicchann-ānañcassa
diṭṭha-dhamma-sukha-vihāraṃ
pācittiy-āpattikkhandhena
janapad-atthā-variya-p-patto
khīṇāpāya-duggativinipāto
dhammānudhamma-p-paṭipannā
dhammānudhamma-p-paṭipanno
dhamma-vicaya-sambojjhaṅgo
passaddhi-sambojjhaṅgassa
dhammānudhamma-p-paṭipatti
jarā-maraṇa-nirodh-agāminiṃ
parikkhīṇa-bhava-saṃyojanā
vicikicchā-pariyuṭṭhitena
caturāsīti-vassa-sahassāni
abhiññā-sacchikaraṇīyassa
seyyāva-satha-padīpeyyassa
yoniso-manasikāra-sampanno
kabaḷīkār-āhāra-bhakkhānaṃ
brahmacariya-pariyosānaṃ
atītānāgata-paccuppannaṃ
aparisuddha-kāya-samācāro
aparisuddha-vacī-samācāro
pabbājanīya-kammārahassa
ukkhepanīya-kammārahassa
nappaṭi-p-passambhetabbaṃ
bhikkhun-ovādaka-sammutiṃ
mūlāya-paṭikassan-ārahena
pārājik-āpatti-k-khandhena
nevasaññā-n-āsaññāyatanaṃ
paranimmita-vasavattīnaṃ
sammā-sambuddha-p-pavedito
diṭṭhi-nijjhāna-k-khantiyā
vimutti-ñāṇa-dassana-kathā
Dutiya-gaṅgāpeyyāla-vagga
nibbidā-virāga-vipannassa
sammā-samādhi-sampannassa
avippaṭisāra-sampannassa
paracitta-pariyāya-kusalo
upekkhā-sati-pārisuddhiṃ
addhāna-magga-p-paṭipanno
uttari-manussa-dhammassa
dāsakamma-kara-porisassa
Nisīdana-paccattharaṇaṃ
addhāna-magga-p-paṭipannā
ceto-parivitakka-maññāya
sabb-ūpadhi-paṭinissaggo
atīt-ānāgata-paccu-p-pannā
cakkhu-samphassa-paccayā
parisuddha-kāya-samācāro
parisuddha-vacī-samācāro
bhikkhun-ovādaka-sammuti
dvemāsa-p-paṭicchannānaṃ
dukkaṭ-āpatti-kkhandhena
yathābhūta-ñāṇa-dassanaṃ
sammā-manasikāra-manvāya
cātuyāma-saṃvara-saṃvuto
sattaratana-samannāgato
piṇḍapāta-paṭikkantānaṃ
passaddhi-sambojjhaṅgaṃ
samādhi-sambojjhaṅgassa
upekkhā-sambojjhaṅgassa
saṅkhār-upādānakkhandho
paccuppanna-dukkhañceva
seyyā-vasatha-padīpeyyaṃ
saṅkhāra-nirodh-agāminiṃ
tiṇa-kaṭṭha-sākhāpalāsaṃ
dhammacariyā-samacariyā
kāmarāga-pariyuṭṭhitena
ākāsānañcāyatana-saññaṃ
viññāṇañcāyatana-saññaṃ
chandarāga-vinay-akkhāyī
Aṭṭhasata-pariyāya-vagga
nevasaññā-āsaññāyatane
iddhipāda-bhāvan-āgāminī
mahāpuñña-k-khandhotveva
uṭṭhāna-vīriy-ādhigatehi
sammā-samādhi-vipannassa
avippaṭisāra-vipannassa
sikkhā-sājīva-samāpanno
uttari-chappañca-vācāhi
punabbhav-ābhinibbatti
somanassa-domanassānaṃ
gāmanigama-rājadhānīsu
anullapan-ādhippāyassā
mālāguḷa-parikkhittāpi
jivhā-samphassa-paccayā
brāhmaṇa-gaha-patikānaṃ
mūlāya-paṭikassan-āraho
gilān-upaṭṭhāka-bhattaṃ
dukkha-nirodh-agāminiyā
tassa-pāpiyasikā-kammaṃ
tajjanīya-kamm-ārahassa
paṭisāraṇīya-kammakato
pañcāha-p-paṭicchannāya
dvemāsa-p-paṭicchannāyo
dvemāsa-p-paṭicchannāya
citta-vipariyāsa-katena
diṭṭha-suta-parisaṅkito
paṭinissajjana-paccayā
samādhi-saṃvattanikāni
anusandhi-vacana-pathaṃ
uccāsayana-mahāsayanaṃ
vipariṇām-aññathābhāvā
icchānaṅgala-vanasaṇḍe
saññā-vedayita-nirodhaṃ
samādhi-saṃvattanikehi
rattandhakā-ratimisāya
hemajāla-paṭicchannāni
brahma-loka-sahabyatāya
Samudaya-dhammānupassī
vīriya-sambojjhaṅgassa
passaddhi-sambojjhaṅgo
viññāṇ-upādānakkhandho
manussa-rāhasseyyakāni
brahmacariy-ānuggahāya
tatth-ev-antara-dhāyiṃsu
paccuppanna-sukhañceva
sasaṅkhāra-parinibbāyī
ākāsānañcāyatana-saññā
viññāṇañcāyatana-saññā
passaddhakāya-saṅkhāro
viññāṇa-nirodh-agāminiṃ
samudaya-dhammānupassī
paligha-parivatti-kampi
byāpāda-pariyuṭṭhitena
diṭṭha-dhamma-vedanīyaṃ
abhiññā-sacchikiriyāya
ākiñcaññāyatana-saññaṃ
mālāgandha-vilepanassa
sāriputta-moggallānesu
dhamma-cakkhu-paṭilābho
rāga-vinaya-pariyosānaṃ
dosa-vinaya-pariyosānaṃ
moha-vinaya-pariyosānaṃ
aṭṭhika-saññā-sahagataṃ
Pañcagati-peyyāla-vagga
āroha-pariṇāha-sampanno
upapatti-paṭilābhiyāni
yathābhūta-ñāṇa-dassane
ākāsānañcāyatana-saññī
viññāṇañcāyatana-saññī
sacitta-pariyāya-kusalo`+
`āpatti-samuṭṭhānānaṃ
piṇḍapāta-paṭikkanto
atikkanta-mānusakena
dukkha-nirodh-agāminī
uttari-manussa-dhammaṃ
saññā-vedayita-nirodhaṃ
samādhi-saṃvattanikehi
brahmacariya-pariyosānaṃ
dhammānudhamma-p-paṭipannā
dhammānudhamma-p-paṭipanno
dhammavicaya-sambojjhaṅgo
diṭṭhadhamma-sukha-vihārānaṃ`+
	
	//abhidhamma and kn
`kakudha-kuṭaja-aṅkola-kaccikāra-kaṇikāra-kaṇṇikāra-kanavera-koraṇḍaka-koviḷāra-kiṃsuka-yodhika-vanamallika-manaṅgaṇa-mana-vajja-bhaṇḍi-surucira-bhaginimālā-malyadhare
Kuravaka-mucalinda-ketaka-vedisa-vañjula-punnāga-bakula-tilaka-piyaka-hasana-sāla-saḷala-campaka-asoka-nāgarukkha-tirīṭi-bhujapatta-lodda-candanoghavane
cāpa-bheda-cāpā-ropanag-gahaṇa-muṭṭhi-p-paṭipīḷana-aṅgulivināmana-pādaṭhapana-saraggahaṇa-sanna-hana-ākaḍḍhana-sandhāraṇa-lakkhaniya-mana-khipane
sattha-g-gahaṇa-chedana-lekhana-vedhana-sall-uddharaṇa-vaṇadhovana-sosana-bhesajj-ānulimpana-vamana-virecan-ānuvāsanakiriya-manusikkhitvā
gaja-gavaja-mahiṃsa-ruru-camara-pasada-khagga-gokaṇṇa-sīha-byaggha-dīpi-accha-koka-taraccha-uddāraka-dali-migabiḷā-rasasa-kaṇṇikānucarite
satipaṭṭhāna-sammappadhāna-iddhipāda-indriya-bala-bojjhaṅga-magga-vara-jhāna-vimokkha-rūpārūpa-santa-sukha-samāpatti-kusalā
āpatt-ānāpatti-garuka-lahuka-satekiccha-atekiccha-vuṭṭhāna-desanā-niggaha-paṭikamma-osāraṇa-nissāraṇa-paṭisāraṇa-kusalā
kurara-cakora-vāraṇam-ayūra-parabhata-jīvañjīvaka-celāvakā-bhiṅkāra-karavīka-matta-vihaṅga-gaṇasa-tata-sam-paghuṭṭhe
uddesa-paripucchā-savana-dhāraṇa-vinicchaya-abhidhamma-vinaya-gāḷha-suttanta-viggahapada-nikkhepapada-sandhi
indriya-bala-bojjhaṅga-maggaṅga-sati-paṭṭhāna-sammappadhāna-iddhipāda-jhāna-vimokkha-samādhi-samāpattīnaṃ
rāga-dosamoha-māna-diṭṭhi-makkha-paḷāsa-issā-macchariya-māyā-sāṭheyya-kuṭila-visama-duccarita-kilesamalehi
issamiga-sākhamiga-sarabhamiga-eṇīmiga-vātamiga-pasadamiga-purisālu-kimpurisa-yakkha-rakkhasa-nisevite
ajjhayana-ajjhāpana-dāna-p-paṭiggahaṇa-dama-saṃyama-niyama-pubba-jinā-ciṇṇa-anusiṭṭhi-paveṇi-vaṃsadharaṇo
sāli-vīhi-yavataṇḍula-tila-mugga-māsa-pubbaṇṇāparaṇṇa-sappitela-navanīta-khīra-dadhi-madhu-guḷa-phāṇitā
añjana-manosilā-haritāla-hiṅgulaka-hema-rajata-kanakā-nekadhā-tusata-vinaddha-paṭimaṇḍita-p-padese
gāmanigama-nagarajana-pada-rukkha-pabbata-nadītaḷāka=pokkharaṇī-migapakkhi-manuja-nara-nārigaṇaṃ
hatthi-assaratha-dhanu-tharu-lekha-muddā-sikkhā-khagga-manta-suti-sammuti-yuddha-yujjhāpana-kiriyā
jhānavimokkha-samādhi-samāpatti-indriya-bala-bojjhaṅga-satipaṭṭhāna-sammappadhāna-iddhipādehi
ajjhayanaajjhāpanadānappaṭiggahaṇadamasaṃyamaniyamapubbamanusiṭṭhipaveṇivaṃsadharaṇo
kāmavitakkabyāpādavitakkavihiṃsāvitakkamānuddhaccadiṭṭhivicikicchākilesavatthūni
nāga-punnāga-sāla-salaḷa-campaka-yūthikā-timuttaka-pāṭaluppala=vassika-mallikā-vicitto
indriya-bala-bojjhaṅga-satipaṭṭhāna-sammappadhāna-iddhipāda-lokiya-lokuttaradhammā
magga-phala-jhāna-vimokkha-samādhi-samāpatti-vipassanā-bhiññā-vividhaguṇa-ratanāni
jātisumana-madhugandhia-dhanu-takkāri-tālīsa-tagaram-usīra-koṭṭha-kacchavitate
ājaññaratha-gaja-turaṅga-dhanadhañña-hiraññasuvaṇṇa-dāsidāsa-bhariya-gāmavaraṃ
paṭṭana-ratanākara-nagara-suṅkaṭṭhāna-verajjaka-chejjabhejja-jana-manusāsanaṃ
sotāpanna-sakadāgāmi-anāgāmi-arahanta-tevijja-chaḷabhiñña-samaṇamaṇi-ratanehi
manāpika-manāpika-khajja-bhojja-leyya-peyya-sāyanīya-bahuvidha-subhanimittena
jāti-jarā-byādhi-maraṇa-soka-parideva-dukkha-domanass-upāyāsa-bhayavinodanāya
vāta-pitta-semha-sannipāta-utupariṇāma-visama-parihāra-opakkamikopakkantaṃ
tiṇa-latā-gaccha-rukkha-osadhi-vanappati-nadī-pabbata-samudda-maccha-kacchapā
manāpika-manāpika-pupphaphala-patta-taca-mūla-sāra-bahuvidha-subhanimittena
manāpika-manāpika-kalyāṇapāpaka-subhāsubha-bahuvidha-vitakka-manasikārena
verambhavāta-samuṭṭhita-kiṃsuka-kiṃsukā-raka-ṇikāra-puppha-cuṇṇa-samokiṇṇā
varadeva-yakkha-rakkhasa-dānava-gandhabba-kinnara-mahorag-ānuciṇṇa-p-padese
dovārika-anīkaṭṭha-pārisajja-negama-bhaṭa-bala-amacca-rājañña-rājūpajīvine
sobbha-sara-sarita-daha-taḷāka-kandarapadara-udapāna-ninna-pokkharaṇi-gataṃ
sobbha-sara-sarita-sākhā-kandarapadara-daha-taḷāka-udapāna-pokkharaṇiyo
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhāra-pariyādānepi
Itarītara-cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārehi
kusal-ākusala-sāvajjānavajja-hīnappaṇīta-kaṇhasukka-sappaṭibhāg-adhamme
surā-sura-garuḷa-gandhabba-yakkha-rakkhasa-mahoraga-kinnara-indabhavanesu
pitta-semha-pubba-ruhira-seda-meda-kheḷa-siṅghāṇika-lasika-muttakarīsā-dīni
Itarītara-cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārehi
amajjava-mañjarī-dhara-pahaṭṭha-puppha-phusita-g-gān-ekapāda-paga-ṇav-itate
sabbabhaya-suñña-khema-abhaya-vara-pavara-nibbānanagara-sampāpana-ṭ-ṭhena
muttāmaṇi-veḷuriya-saṅkha-silā-pavāḷa-phalikamaṇi-vividha-ratana-nicayaṃ
nindā-pasaṃsā-sukhadukkha-sammānana-vimānana-bahuvidha-dosa-ūmivegañca
pāsāda-kuṭi-leṇaguhā-pabbhāra-dari-bila-giri-vivara-pabbatantara-gatopi
manāpika-manāpika-saṇha-sukhuma-mudumaddava-bahuvidha-subhanimittena
aparimita-vividha-vipula-parisuddha-vijjāvimuttipupphasaṅkusumitaṃ
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārānantipi
ācārasīla-guṇavatta-p-paṭivatta-bahuvidha-dhamma-saṅghāṭ-asamavāyena
cīvara-piṇḍapāta-senāsana-gilāna-p-paccaya-bhesajja-parikkhārānanti
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhārānanti
sanegama-jānapada-bhaṭa-bala-brāhmaṇagaha-patika-amacca-janamajjhe
tiṇa-purisaka-chakaṇa-tiṇa-palāla-mattikāpuñja-phalakala-k-khavedhe
duccarita-duggati-visama-kantāra-vipāka-vinipāta-kilesajāla-jaṭite
sithila-dhanita-dīgha-rassa-garuka-lahuka-k-khara-pariccheda-kusalā
nirantaram-akhaṇḍa-c-chiddam-asusira-bahala-ghana-vitthiṇṇa-sīlena
hima-girisikhara-saṅkāsa-varabhava-nasa-tasa-hassa-p-paṭimaṇḍitaṃ
pāsāṇasakkhara-khara-marumba-āvaṭṭa-gaggalaka-ūmika-vaṅka-cadika
udakāharaṇa-gharasammajjana-dantakaṭṭha-mukhodakānu-p-padānena
anicc-ucchādana-parimaddana-bhedana-vikiraṇa-viddhaṃsana-dhammo
rūpa-sadda-gandha-rasa-phassa-puttadāra-dāsa-kammakara-porisañca
ākiṇṇa-nela-maṇḍala-mahāvarāha-nāgakula-kareṇusaṅghā-dhivuṭṭhe
paripuṇṇa-pīṇita-pahaṭṭha-lobhanīya-santa-sukha-samāpattilābhī
cīvara-piṇḍapāta-senāsana-gilāna-paccaya-bhesajja-parikkhāraṃ
inda-yama-varuṇa-kuvera-pajāpati-suyāma-santusita-loka-pālehipi
jāti-jarā-byādhi-maraṇa-soka-parideva-dukkha-domanass-upāyāsehi
gambhīra-nipuṇa-duddasa-duranubodha-sukhuma-duppaṭivedhataṃ
parabhaṇḍana-kalaha-viggaha-vivāda-ritta-j-jhāna-aratijananaṃ
aneka-vividha-atiparama-dukkarakārika-lūkha-jīvit-ānuyogena
sīla-samādhi-paññā-vimutti-vimuttiñāṇa-dassana-paribhāvitaṃ
gaja-turaṅga-ratha-suvaṇṇa-rajatam-aṇim-uttā-itthiratanā-dīni
parisuddha-vimala-nikkaṇṭaka-paṇḍaravara-p-pavara-sāsanato
ucchiṭṭha-paṭiggahaṇa-ucchādana-nahāpana-pādaparikammena
ahikukkura-manussakuṇapa-sarīravaḷañja-koṭṭhāsarāsi-gato
muttākalāpa-maṇikalāpa-pavāḷakalāpā-bharaṇa-p-paṭimaṇḍito
itarītara-gilānapaccaya-bhesajja-parikkhāra-santuṭṭhiyā
ācārasīla-guṇavatta-paṭipatti-vimala-nava-salila-sampuṇṇo
amacca-bhaṭa-bala-dovārika-anīkaṭṭha-pārisajja-janamajjhe
guṇarāsi-guṇapuñja-aparimita-asaṅkhyeyya-appameyyaguṇaṃ
Āsavavippayutta-nasā-savana-anidassana-sappaṭigha-mūlepi
suppa-sāritā-neka-vidhava-rabhaṇḍa-paripūrit-antarāpaṇaṃ
īsāakkha-cakkaratha-pañjara-ratha-daṇḍa-yuga-rasmi-patodā
sārava-rapavara-abhijāta-jātimanta-ratta-lohitacandanaṃ
tiparivaṭṭa-dvādasākāra-catusaccābhi-samayappaṭivedhe
susaṇṭhitamakampitama-luḷita-sabhāva-parisuddhā-cārena
atimuttaka-saṅkusumita-latā-vitata-paṭimaṇḍitappadese
manāpika-manāpika-gītavādita-bahuvidha-subhanimittena
Yasodharā-pamukha-aṭṭhārasa-bhikkhunī-sahassa-apadāna
Yasodharā-pamukha-aṭṭhārasa-bhikkhunī-sahass-āpadānaṃ
sallekhitācāra-p-paṭipatti-dhutaṅgaguṇa-dharanissitā
kilesavassa-tividhaggi-santāpātapa-paṭibāhanaṭṭhena
suci-vimala-vippasannamanā-vila-dhammavara-vāripuṇṇaṃ
Vinīlaka-vipubbaka-uddhumātaka-samuggahaṇa-lakkhaṇā
Yasavatīpamukha-aṭṭhārasa-bhikkhunī-sahassa-apadāna
Yasavatīpamukha-aṭṭhārasa-bhikkhunī-sahass-āpadānaṃ
gambhīra-parikhā-paṇḍara-pākāra-parikkhitt-antepuraṃ
kāsika-koṭumbarikā-dinā-nāv-idha-vatthāpaṇa-sampannaṃ
samādhikkhandha-dhammasāra-sīlasākhā-parivitthiṇṇā
amacca-bhaṭa-bala-dovārika-anīkaṭṭha-pārisajja-janehi
sallekhitācāra-p-paṭipatti-dhuta-varaṅ-gaguṇa-nissitā
sakala-loka-thuta-thomita-mahati-mahā-sobhanakaraṇāya
lābhasakkāra-siloka-paṭisaṃyutta-vitakkavaḍḍhanaṃ
ācārasīla-guṇavatta-paṭipatti-sallekha-dhutaguṇena
sugatāgama-pariyatti-ācāra-saṃyama-sīlasaṃvara-guṇā
āveṭhana-viniveṭhana-kaḍḍhana-niggaha-p-paṭikammena
ucchādana-parimaddana-nahāpana-sambāhanam-attakena
kāmataṇhā-bhavataṇhā-vibhavataṇhā-pipāsāvinayanaṃ
vimalakhīṇāsava-balappatta-vasībhūta-mahābhūtānaṃ
sukhasamphassa-mahati-mahāsiri-sayana-pariyesanena
sāsaṅka-sappaṭibhaya-visama-kantāra-taraṇasamattho
anavajja-nipuṇa-sukhuma-santi-sukham-anatikkamanāya
Akkhabbhañjana-vaṇa-paṭicchādana-putta-maṃsūpamaṃ
Kusalavipāka-manoviññāṇadhātu-somanassasahagata
neva-vipāka-navipāka-dhammadhamma-citta-samaṅgissa
nānādhātu-anekadhātu-vinibbhoga-mapaccavekkhato
sampati-virūḷha-sucigandha-manuñña-māvakappadese
Aniccasaññā-dukkhasaññā-asamanupassana-lakkhaṇā
lokāyata-vitaṇḍa-janasallāpa-plava-citta-kotūhalo
agalu-tagara-tālīsa-kalo-hita-candanānulitta-gatto
parūpa-sevana-piya-samullāpa-pacchā-pure-dhāvanena
sabbasām-añña-guṇa-pariyesana-avisaṃvādakaṭṭhena
lābha-yasasa-k-kāramāna-nav-andana-pūjana-apacitīsu
susaṇṭhita-makam-pitamaluḷita-sabhāva-parisuddho
Navattabbaṃ-saṃghassa-dinnaṃ-mahapphalantikathā
Navattabbaṃ-buddhassa-dinnaṃ-mahapphalantikathā
somanassavippayutta-upekkhāvippayutta-cittassa
upekkhāvippayutta-somanassavippayutta-cittassa
paccuppannārammaṇa-paccuppannacitta-samaṅgissa
Patthana-ganthana-abhisaṅkhārakāya-saṅkhāraṇaṃ
ḍaṃsa-makasa-vātātapa-sarīsapa-samphassa-dukkhaṃ
Yasodharā-pamukha-dasa-bhikkhunī-sahassa-apadāna
Yasodharā-pamukha-dasa-bhikkhunī-sahass-āpadānaṃ
suppasārita-rucirabahu-vidha-pupphagandhā-paṇaṃ
kahāpaṇa-rajata-suvaṇṇa-kaṃsa-patthara-paripūraṃ
ruṇṇa-kāruñña-kandita-paridevita-lālappita-mukhā
aparimita-vividha-vipula-vīci-puppha-saṅkusumito
jātikantāra-kilesavanagahana-nittharaṇ-aṭṭhena
anekavidha-sāmañña-guṇavara-ratanuṭṭhānaṭṭhena
lābhasakkāra-siloka-vandana-mānana-pūjana-kāraṇā
Kusalavipāka-manoviññāṇadhātu-upekkhāsahagata
diṭṭhigata-vippayutta-lobhasahagata-cittuppādā
diṭṭhigata-sampayutta-lobhasahagata-cittuppādā
Asaṅgahitena-sampayutta-vippayutta-pada-niddesa
Navattabbaṃ-saṃghodakkhiṇaṃ-paṭiggaṇhāti-kathā
somanassasampayutta-saddhāvippayutta-cittassa
somanassasampayutta-saddhāsampayutta-cittassa
saddhāsampayutta-somanassavippayutta-cittassa
saddhāsampayutta-somanassasampayutta-cittassa
somanassavippayutta-saddhāsampayutta-cittassa
somanassavippayutta-saddhāvippayutta-cittassa
saddhāvippayutta-somanassasampayutta-cittassa
saddhāvippayutta-somanassavippayutta-cittassa
Cittasaṃsaṭṭha-samuṭṭhāna-duka-abyākata-sadisaṃ
Na-āsavasampayutta-na-anidassana-sappaṭigha-mūle
kāḷāgaru-padmaka-piyaṅgu-devadāruka-cocagahane
gilāna-paccaya-bhesajja-parikkhāra-palibodhena
soka-parideva-dukkha-domanass-upāyāsa-dukkhassa
Sekhā-sekha-vipassanā-pubbaṅgama-p-pahāna-yogena
sīla-samādhi-paññā-vimutti-bala-samattha-bhāvena
sanegamajānapada-amacca-bhaṭa-bala-mahāmattehi
siniddha-sama-sumajjita-sappabhāsa-vimalā-dāsaṃ
ārām-uyyāna-taḷāka-pokkharaṇi-udapāna-sampannaṃ
sannaddha-sajja-mahati-mahāsattha-pariyesanena
gahaṇā-pagata-uru-visaṭa-vitthata-mahantaṭṭhena
samatha-vipassanā-magga-phala-nibbāna-dassanāya
inna-bhagga-saṅkuṭita-sañchinna-gatinīvaraṇo
bahuvidha-ūmittha-nitavega-visaṭa-māvaṭṭavegaṃ
daṭṭha-phuṭṭha-diṭṭha-asita-pīta-khāyita-sāyitaṃ
Saṅgahi-tena-sampayutta-vippayuttapada-niddesa
Navattabbaṃ-saṃghodakkhiṇaṃ-visodhetītikathā
somanassasampayutta-pacchimacitta-samaṅgīnaṃ
piyavippayoga-vipariṇāma-paritāpana-lakkhaṇo
nimittaggahaṇa-anubyañjanaggahaṇa-vinodanaṃ
vijjādhara-siddha-samaṇa-tāpasa-gaṇ-ādhivuṭṭhe
soka-parideva-dukkha-domanass-upāyāsa-dhammato
soka-parideva-dukkha-domanass-upāyāsa-kantāraṃ
anavaññatti-paṭisaṃyutta-vitakka-vaḍḍhananti
caturāsīti-brāhmaṇakaññā-bhikkhunī-sahassāni
ārām-uyyānopavana-taḷāka-pokkharaṇi-sampannaṃ
vividha-samaṇabrāhmaṇa-sabhājana-saṅghaṭitaṃ
atthadhamma-nirutti-paṭibhāna-paṭisambhidāsu
ahinakula-biḷāra-koṭṭhuka-sūkara-migapakkhino
sañcuṇṇitaṭṭhimaṃ-sadha-manichinna-parigatto
arahanta-vimalakhīṇāsava-mahābhūta-bhavanato
sabba-dukkha-jighacchā-dubbalya-paṭivinodanaṃ
patthit-icchita-sabbasampatti-varadadaṭṭhena
aparimita-manantama-pāramakkhobhita-gambhīre
vimutti-vara-kusuma-pupphit-ārammaṇa-van-antare
Sampayuttena-saṅgahitā-saṅgahitapada-niddesa
Vippayuttena-saṅgahitā-saṅgahitapada-niddesa
Vippayuttena-saṅgahitā-saṅgahitapada-niddeso
kusalavippayutta-akusalavippayutta-cittassa
akusalavippayutta-kusalavippayutta-cittassa
somanassasampayutta-ñāṇavippayutta-cittassa
somanassasampayutta-ñāṇasampayutta-cittassa
ñāṇasampayutta-somanassavippayutta-cittassa
ñāṇasampayutta-somanassasampayutta-cittassa
upekkhāsampayutta-saddhāvippayutta-cittassa
upekkhāsampayutta-saddhāsampayutta-cittassa
saddhāsampayutta-upekkhāvippayutta-cittassa
saddhāsampayutta-upekkhāsampayutta-cittassa
somanassavippayutta-ñāṇasampayutta-cittassa
somanassavippayutta-ñāṇavippayutta-cittassa
ñāṇavippayutta-somanassasampayutta-cittassa
ñāṇavippayutta-somanassavippayutta-cittassa
upekkhāvippayutta-saddhāsampayutta-cittassa
upekkhāvippayutta-saddhāvippayutta-cittassa
saddhāvippayutta-upekkhāsampayutta-cittassa
saddhāvippayutta-upekkhāvippayutta-cittassa
vipākābyākata-kiriyābyākata-cittasamaṅgissa
Paṭhama-sikkhamāna-navuṭṭhāpana-sikkhāpadaṃ
akkharapada-byañjana-ākāra-nirutti-niddesehi
bala-bojjhaṅga-vimokkha-samādhi-samāpattīnaṃ
aneka-rukkha-vividha-vikati-phalam-āharantiyo
soka-parideva-dukkha-domanass-upāyāsa-dukkhaṃ
ākāsānañcāyatana-samāpatti-paṭilābhatthāya
soka-parideva-dukkha-domanass-upāyāsa-nissitā
parānudayatā-paṭisaṃyutta-vitakkavaḍḍhanaṃ
sakkāyadiṭṭhi-vicikicchā-sīlabbataparāmāsā
vīmaṃsāsamādhi-padhānasaṅkhāra-samannāgato
Vīmaṃsāsamādhi-padhānasaṅkhāra-samannāgate
Suvibhatta-vīthi-caccara-catukka-siṅghāṭakaṃ
bahuvidha-khajja-bhojja-leyya-peyya-sāyanīyaṃ
Nānādhammā-naṃe-kakicca-abhinipphādana-pañha
abhivādana-paccuṭṭhāna-sammānana-pūjanāraho
aggavara-vimutti-paṇḍara-vimala-setacchattaṃ
sīlavara-pavara-asama-sucigandha-paribhāvito
paṭipannaka-phalaṭṭha-sekkha-phala-samaṅgīhi
upekkhāsampayutta-pacchimacitta-samaṅgīnaṃ
pītisahagata-sukhasahagata-cittasamaṅgissa
mahaggatārammaṇa-mahaggata-cittasamaṅgissa
anāgatārammaṇa-paccuppanna-cittasamaṅgissa
diṭṭhigata-vippayutta-lobhasahagat-ādhipati
Cittasaṃsaṭṭha-samuṭṭhān-ānuparivatti-dukaṃ
nano-cittasaṃsaṭṭha-samuṭṭhān-ānuparivattiṃ`;